package openai

import (
	"encoding/json"
	"fmt"
)

// ChatCompletionContentPartUnionParam holds exactly one user content part
// variant.
type ChatCompletionContentPartUnionParam struct {
	OfText     *ChatCompletionContentPartTextParam  `json:"-"`
	OfImageURL *ChatCompletionContentPartImageParam `json:"-"`
	OfFile     *ChatCompletionContentPartFileParam  `json:"-"`
}

func (u ChatCompletionContentPartUnionParam) MarshalJSON() ([]byte, error) {
	switch {
	case u.OfText != nil:
		return json.Marshal(u.OfText)
	case u.OfImageURL != nil:
		return json.Marshal(u.OfImageURL)
	case u.OfFile != nil:
		return json.Marshal(u.OfFile)
	default:
		return nil, fmt.Errorf("openai: empty union ChatCompletionContentPartUnionParam")
	}
}

func TextContentPart(text string) ChatCompletionContentPartUnionParam {
	return ChatCompletionContentPartUnionParam{
		OfText: &ChatCompletionContentPartTextParam{
			Type: ContentTypeText,
			Text: text,
		},
	}
}

func ImageContentPart(imageURL ChatCompletionContentPartImageImageURLParam) ChatCompletionContentPartUnionParam {
	return ChatCompletionContentPartUnionParam{
		OfImageURL: &ChatCompletionContentPartImageParam{
			Type:     ContentTypeImageURL,
			ImageURL: imageURL,
		},
	}
}

func FileContentPart(file ChatCompletionContentPartFileFileParam) ChatCompletionContentPartUnionParam {
	return ChatCompletionContentPartUnionParam{
		OfFile: &ChatCompletionContentPartFileParam{
			Type: ContentTypeFile,
			File: file,
		},
	}
}

type ChatCompletionContentPartTextParam struct {
	// The text content.
	Text string `json:"text"`
	// The type of the content part. Defaults to "text" when left empty.
	Type string `json:"type"`
}

func (r ChatCompletionContentPartTextParam) MarshalJSON() ([]byte, error) {
	if r.Type == "" {
		r.Type = ContentTypeText
	}
	type shadow ChatCompletionContentPartTextParam
	return json.Marshal(shadow(r))
}

type ChatCompletionContentPartImageParam struct {
	ImageURL ChatCompletionContentPartImageImageURLParam `json:"image_url"`
	// The type of the content part. Defaults to "image_url" when left empty.
	Type string `json:"type"`
}

func (r ChatCompletionContentPartImageParam) MarshalJSON() ([]byte, error) {
	if r.Type == "" {
		r.Type = ContentTypeImageURL
	}
	type shadow ChatCompletionContentPartImageParam
	return json.Marshal(shadow(r))
}

type ChatCompletionContentPartImageImageURLParam struct {
	// Either a URL of the image or the base64 encoded image data.
	URL string `json:"url"`
	// Specifies the detail level of the image.
	//
	// Any of "auto", "low", "high".
	Detail string `json:"detail,omitempty"`
}

type ChatCompletionContentPartFileParam struct {
	File ChatCompletionContentPartFileFileParam `json:"file"`
	// The type of the content part. Defaults to "file" when left empty.
	Type string `json:"type"`
}

func (r ChatCompletionContentPartFileParam) MarshalJSON() ([]byte, error) {
	if r.Type == "" {
		r.Type = ContentTypeFile
	}
	type shadow ChatCompletionContentPartFileParam
	return json.Marshal(shadow(r))
}

type ChatCompletionContentPartFileFileParam struct {
	// The base64 encoded file data, used when passing the file to the model as a
	// string.
	FileData *string `json:"file_data,omitzero"`
	// The ID of an uploaded file to use as input.
	FileID *string `json:"file_id,omitzero"`
	// The name of the file, used when passing the file to the model as a string.
	Filename *string `json:"filename,omitzero"`
}

type ChatCompletionContentPartRefusalParam struct {
	// The refusal message generated by the model.
	Refusal string `json:"refusal"`
	// The type of the content part. Defaults to "refusal" when left empty.
	Type string `json:"type"`
}

func (r ChatCompletionContentPartRefusalParam) MarshalJSON() ([]byte, error) {
	if r.Type == "" {
		r.Type = ContentTypeRefusal
	}
	type shadow ChatCompletionContentPartRefusalParam
	return json.Marshal(shadow(r))
}
