package sdk

import (
	constant "github.com/zhongys/Daksha.git/internal/ai/sdk/shared"
)

type ChatCompletionChunk struct {
	// A unique identifier for the chat completion. Each chunk has the same ID.
	ID string `json:"id" api:"required"`
	// A list of chat completion choices. Can contain more than one elements if `n` is
	// greater than 1. Can also be empty for the last chunk if you set
	// `stream_options: {"include_usage": true}`.
	Choices []ChatCompletionChunkChoice `json:"choices" api:"required"`
	// The Unix timestamp (in seconds) of when the chat completion was created. Each
	// chunk has the same timestamp.
	Created int64 `json:"created" api:"required" format:"unixtime"`
	// The model to generate the completion.
	Model string `json:"model" api:"required"`
	// The object type, which is always `chat.completion.chunk`.
	Object string `json:"object" default:"chat.completion.chunk"`
	// Moderation results for the request input and generated output. Present on the
	// moderation chunk when moderated completions are requested.
	Moderation ChatCompletionChunkModeration `json:"moderation,omitempty"`
	// Specifies the processing type used for serving the request.
	//
	//   - If set to 'auto', then the request will be processed with the service tier
	//     configured in the Project settings. Unless otherwise configured, the Project
	//     will use 'default'.
	//   - If set to 'default', then the request will be processed with the standard
	//     pricing and performance for the selected model.
	//   - If set to '[flex](https://platform.openai.com/docs/guides/flex-processing)' or
	//     '[priority](https://openai.com/api-priority-processing/)', then the request
	//     will be processed with the corresponding service tier.
	//   - When not set, the default behavior is 'auto'.
	//
	// When the `service_tier` parameter is set, the response body will include the
	// `service_tier` value based on the processing mode actually used to serve the
	// request. This response value may be different from the value set in the
	// parameter.
	//
	// Any of "auto", "default", "flex", "scale", "priority".
	ServiceTier ChatCompletionChunkServiceTier `json:"service_tier" api:"nullable"`
	// This fingerprint represents the backend configuration that the model runs with.
	// Can be used in conjunction with the `seed` request parameter to understand when
	// backend changes have been made that might impact determinism.
	//
	// Deprecated: deprecated
	SystemFingerprint string `json:"system_fingerprint"`
	// An optional field that will only be present when you set
	// `stream_options: {"include_usage": true}` in your request. When present, it
	// contains a null value **except for the last chunk** which contains the token
	// usage statistics for the entire request.
	//
	// **NOTE:** If the stream is interrupted or cancelled, you may not receive the
	// final usage chunk which contains the total token usage for the request.
	Usage CompletionUsage `json:"usage" api:"nullable"`
}

type CompletionUsage struct {
	// Number of tokens in the generated completion.
	CompletionTokens int64 `json:"completion_tokens" api:"required"`
	// Number of tokens in the prompt.
	PromptTokens int64 `json:"prompt_tokens" api:"required"`
	// Total number of tokens used in the request (prompt + completion).
	TotalTokens int64 `json:"total_tokens" api:"required"`
	// Breakdown of tokens used in a completion.
	CompletionTokensDetails CompletionUsageCompletionTokensDetails `json:"completion_tokens_details"`
	// Breakdown of tokens used in the prompt.
	PromptTokensDetails CompletionUsagePromptTokensDetails `json:"prompt_tokens_details"`
}

type CompletionUsageCompletionTokensDetails struct {
	// When using Predicted Outputs, the number of tokens in the prediction that
	// appeared in the completion.
	AcceptedPredictionTokens int64 `json:"accepted_prediction_tokens"`
	// Audio input tokens generated by the model.
	AudioTokens int64 `json:"audio_tokens"`
	// Tokens generated by the model for reasoning.
	ReasoningTokens int64 `json:"reasoning_tokens"`
	// When using Predicted Outputs, the number of tokens in the prediction that did
	// not appear in the completion. However, like reasoning tokens, these tokens are
	// still counted in the total completion tokens for purposes of billing, output,
	// and context window limits.
	RejectedPredictionTokens int64 `json:"rejected_prediction_tokens"`
}

type CompletionUsagePromptTokensDetails struct {
	// Audio input tokens present in the prompt.
	AudioTokens int64 `json:"audio_tokens"`
	// Cached tokens present in the prompt.
	CachedTokens int64 `json:"cached_tokens"`
}

type ChatCompletionChunkChoice struct {
	// A chat completion delta generated by streamed model responses.
	Delta ChatCompletionChunkChoiceDelta `json:"delta" api:"required"`
	// The reason the model stopped generating tokens. This will be `stop` if the model
	// hit a natural stop point or a provided stop sequence, `length` if the maximum
	// number of tokens specified in the request was reached, `content_filter` if
	// content was omitted due to a flag from our content filters, `tool_calls` if the
	// model called a tool, or `function_call` (deprecated) if the model called a
	// function.
	//
	// Any of "stop", "length", "tool_calls", "content_filter", "function_call".
	FinishReason string `json:"finish_reason" api:"required"`
	// The index of the choice in the list of choices.
	Index int64 `json:"index" api:"required"`
	// Log probability information for the choice.
	Logprobs ChatCompletionChunkChoiceLogprobs `json:"logprobs" api:"nullable"`
}

type ChatCompletionChunkChoiceDelta struct {
	// The contents of the chunk message.
	Content string `json:"content" api:"nullable"`
	// The refusal message generated by the model.
	Refusal string `json:"refusal" api:"nullable"`
	// The role of the author of this message.
	//
	// Any of "developer", "system", "user", "assistant", "tool".
	Role      string                                   `json:"role"`
	ToolCalls []ChatCompletionChunkChoiceDeltaToolCall `json:"tool_calls"`
}

type ChatCompletionChunkChoiceDeltaToolCall struct {
	Index int64 `json:"index" api:"required"`
	// The ID of the tool call.
	ID       string                                         `json:"id"`
	Function ChatCompletionChunkChoiceDeltaToolCallFunction `json:"function"`
	// The type of the tool. Currently, only `function` is supported.
	//
	// Any of "function".
	Type string `json:"type"`
}

type ChatCompletionChunkChoiceDeltaToolCallFunction struct {
	// The arguments to call the function with, as generated by the model in JSON
	// format. Note that the model does not always generate valid JSON, and may
	// hallucinate parameters not defined by your function schema. Validate the
	// arguments in your code before calling your function.
	Arguments string `json:"arguments"`
	// The name of the function to call.
	Name string `json:"name"`
}

type ChatCompletionChunkChoiceLogprobs struct {
	// A list of message content tokens with log probability information.
	Content []ChatCompletionTokenLogprob `json:"content" api:"required"`
	// A list of message refusal tokens with log probability information.
	Refusal []ChatCompletionTokenLogprob `json:"refusal" api:"required"`
}

type ChatCompletionChunkModeration struct {
	// Moderation for the request input.
	Input ChatCompletionChunkModerationInputUnion `json:"input,omitempty" api:"required"`
	// Moderation for the generated output.
	Output ChatCompletionChunkModerationOutputUnion `json:"output,omitempty" api:"required"`
}

type ChatCompletionChunkModerationInputUnion struct {
	// This field is from variant
	// [ChatCompletionChunkModerationInputModerationResults].
	Model string `json:"model,omitempty"`
	// This field is from variant
	// [ChatCompletionChunkModerationInputModerationResults].
	Results []ChatCompletionChunkModerationInputModerationResultsResult `json:"results,omitempty"`
	// Any of "moderation_results", "error".
	Type string `json:"type"`
	// This field is from variant [ChatCompletionChunkModerationInputError].
	Code string `json:"code,omitempty"`
	// This field is from variant [ChatCompletionChunkModerationInputError].
	Message string `json:"message,omitempty"`
}

type anyChatCompletionChunkModerationInput interface {
	implChatCompletionChunkModerationInputUnion()
}

func (ChatCompletionChunkModerationInputModerationResults) implChatCompletionChunkModerationInputUnion() {
}

func (ChatCompletionChunkModerationInputError) implChatCompletionChunkModerationInputUnion() {}

func (u ChatCompletionChunkModerationInputUnion) AsAny() anyChatCompletionChunkModerationInput {
	switch u.Type {
	case constant.ModerationTypeResults:
		return u.AsModerationResults()
	case constant.ModerationTypeError:
		return u.AsError()
	}
	return nil
}

func (u ChatCompletionChunkModerationInputUnion) AsModerationResults() (v ChatCompletionChunkModerationInputModerationResults) {
	v.Model = u.Model
	v.Results = u.Results
	v.Type = u.Type
	return v
}

func (u ChatCompletionChunkModerationInputUnion) AsError() (v ChatCompletionChunkModerationInputError) {
	v.Message = u.Message
	v.Code = u.Code
	v.Type = u.Type
	return v
}

type ChatCompletionChunkModerationInputModerationResults struct {
	// The moderation model used to generate the results.
	Model string `json:"model" api:"required"`
	// A list of moderation results.
	Results []ChatCompletionChunkModerationInputModerationResultsResult `json:"results" api:"required"`
	// The object type, which is always `moderation_results`.
	Type string `json:"type" default:"moderation_results"`
}

type ChatCompletionChunkModerationInputModerationResultsResult struct {
	// A dictionary of moderation categories to booleans, True if the input is flagged
	// under this category.
	Categories map[string]bool `json:"categories" api:"required"`
	// Which modalities of input are reflected by the score for each category.
	CategoryAppliedInputTypes map[string][]string `json:"category_applied_input_types" api:"required"`
	// A dictionary of moderation categories to scores.
	CategoryScores map[string]float64 `json:"category_scores" api:"required"`
	// A boolean indicating whether the content was flagged by any category.
	Flagged bool `json:"flagged" api:"required"`
	// The moderation model that produced this result.
	Model string `json:"model" api:"required"`
	// The object type, which was always `moderation_result` for successful moderation
	// results.
	Type string `json:"type" default:"moderation_result"`
}

type ChatCompletionChunkModerationInputError struct {
	// The error code.
	Code string `json:"code" api:"required"`
	// The error message.
	Message string `json:"message" api:"required"`
	// The object type, which is always `error`.
	Type string `json:"type" default:"error"`
}

type ChatCompletionChunkModerationOutputUnion struct {
	// This field is from variant
	// [ChatCompletionChunkModerationOutputModerationResults].
	Model string `json:"model"`
	// This field is from variant
	// [ChatCompletionChunkModerationOutputModerationResults].
	Results []ChatCompletionChunkModerationOutputModerationResultsResult `json:"results"`
	// Any of "moderation_results", "error".
	Type string `json:"type"`
	// This field is from variant [ChatCompletionChunkModerationOutputError].
	Code string `json:"code"`
	// This field is from variant [ChatCompletionChunkModerationOutputError].
	Message string `json:"message"`
}

type anyChatCompletionChunkModerationOutput interface {
	implChatCompletionChunkModerationOutputUnion()
}

func (ChatCompletionChunkModerationOutputModerationResults) implChatCompletionChunkModerationOutputUnion() {
}
func (ChatCompletionChunkModerationOutputError) implChatCompletionChunkModerationOutputUnion() {}

func (u ChatCompletionChunkModerationOutputUnion) AsAny() anyChatCompletionChunkModerationOutput {
	switch u.Type {
	case constant.ModerationTypeResult:
		return u.AsModerationResults()
	case constant.ModerationTypeError:
		return u.AsError()
	}
	return nil
}

func (u ChatCompletionChunkModerationOutputUnion) AsModerationResults() (v ChatCompletionChunkModerationOutputModerationResults) {
	v.Model = u.Model
	v.Results = u.Results
	v.Type = u.Type
	return v
}

func (u ChatCompletionChunkModerationOutputUnion) AsError() (v ChatCompletionChunkModerationOutputError) {
	v.Message = u.Message
	v.Code = u.Code
	v.Type = u.Type
	return v
}

type ChatCompletionChunkModerationOutputModerationResults struct {
	// The moderation model used to generate the results.
	Model string `json:"model" api:"required"`
	// A list of moderation results.
	Results []ChatCompletionChunkModerationOutputModerationResultsResult `json:"results" api:"required"`
	// The object type, which is always `moderation_results`.
	Type string `json:"type" default:"moderation_results"`
}

type ChatCompletionChunkModerationOutputModerationResultsResult struct {
	// A dictionary of moderation categories to booleans, True if the input is flagged
	// under this category.
	Categories map[string]bool `json:"categories" api:"required"`
	// Which modalities of input are reflected by the score for each category.
	CategoryAppliedInputTypes map[string][]string `json:"category_applied_input_types" api:"required"`
	// A dictionary of moderation categories to scores.
	CategoryScores map[string]float64 `json:"category_scores" api:"required"`
	// A boolean indicating whether the content was flagged by any category.
	Flagged bool `json:"flagged" api:"required"`
	// The moderation model that produced this result.
	Model string `json:"model" api:"required"`
	// The object type, which was always `moderation_result` for successful moderation
	// results.
	Type string `json:"type" default:"moderation_result"`
}

type ChatCompletionChunkModerationOutputError struct {
	// The error code.
	Code string `json:"code" api:"required"`
	// The error message.
	Message string `json:"message" api:"required"`
	// The object type, which is always `error`.
	Type string `json:"type" default:"error"`
}

type ChatCompletionChunkServiceTier string

const (
	ChatCompletionChunkServiceTierAuto     ChatCompletionChunkServiceTier = "auto"
	ChatCompletionChunkServiceTierDefault  ChatCompletionChunkServiceTier = "default"
	ChatCompletionChunkServiceTierFlex     ChatCompletionChunkServiceTier = "flex"
	ChatCompletionChunkServiceTierScale    ChatCompletionChunkServiceTier = "scale"
	ChatCompletionChunkServiceTierPriority ChatCompletionChunkServiceTier = "priority"
)


