package sdk

import (
	"context"
	"net/http"
	"slices"

	"github.com/zhongys/Daksha.git/internal/ai/sdk/option"
	requestconfig "github.com/zhongys/Daksha.git/internal/ai/sdk/requestConfig"
	constant "github.com/zhongys/Daksha.git/internal/ai/sdk/shared"
	"github.com/zhongys/Daksha.git/internal/ai/sdk/ssestream"
)

type ChatCompletionService struct {
	Options []option.RequestOption
	// Given a list of messages comprising a conversation, the model will return a
	// response.
	Messages ChatCompletionMessageService
}

func NewChatCompletionService(opts ...option.RequestOption) (r ChatCompletionService) {
	r = ChatCompletionService{}
	r.Options = opts
	r.Messages = NewChatCompletionMessageService(opts...)
	return
}

func (r *ChatCompletionService) New(ctx context.Context, body ChatCompletionNewParams, opts ...option.RequestOption) (res *ChatCompletion, err error) {
	var preClientOpts = []option.RequestOption{requestconfig.WithBearerAuthSecurity()}
	opts = slices.Concat(preClientOpts, r.Options, opts)
	path := "chat/completions"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

func (r *ChatCompletionService) NewStreaming(ctx context.Context, body ChatCompletionNewParams, opts ...option.RequestOption) (stream *ssestream.Stream[ChatCompletionChunk]) {
	var (
		raw *http.Response
		err error
	)
	var preClientOpts = []option.RequestOption{requestconfig.WithBearerAuthSecurity()}
	opts = slices.Concat(preClientOpts, r.Options, opts)
	opts = append(opts, option.WithJSONSet("stream", true))
	path := "chat/completions"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &raw, opts...)
	return ssestream.NewStream[ChatCompletionChunk](ssestream.NewDecoder(raw), err)
}

type ChatCompletion struct {
	// A unique identifier for the chat completion.
	ID string `json:"id"`
	// A list of chat completion choices. Can be more than one if `n` is greater
	// than 1.
	Choices []ChatCompletionChoice `json:"choices"`
	// The Unix timestamp (in seconds) of when the chat completion was created.
	Created int64 `json:"created" format:"unixtime"`
	// The model used for the chat completion.
	Model string `json:"model"`
	// The object type, which is always `chat.completion`.
	Object string `json:"object" default:"chat.completion"`
	// Moderation results for the request input and generated output, if moderated
	// completions were requested.
	Moderation ChatCompletionModeration `json:"moderation"`
	// Specifies the processing type used for serving the request.
	//
	//   - If set to 'auto', then the request will be processed with the service tier
	//     configured in the Project settings. Unless otherwise configured, the Project
	//     will use 'default'.
	//   - If set to 'default', then the request will be processed with the standard
	//     pricing and performance for the selected model.
	//   - If set to '[flex](https://platform.openai.com/docs/guides/flex-processing)' or
	//     '[priority](https://openai.com/api-priority-processing/)', then the request
	//     will be processed with the corresponding service tier.
	//   - When not set, the default behavior is 'auto'.
	//
	// When the `service_tier` parameter is set, the response body will include the
	// `service_tier` value based on the processing mode actually used to serve the
	// request. This response value may be different from the value set in the
	// parameter.
	//
	// Any of "auto", "default", "flex", "scale", "priority".
	ServiceTier ChatCompletionServiceTier `json:"service_tier" `
	// This fingerprint represents the backend configuration that the model runs with.
	//
	// Can be used in conjunction with the `seed` request parameter to understand when
	// backend changes have been made that might impact determinism.
	//
	// Deprecated: deprecated
	SystemFingerprint string `json:"system_fingerprint"`
	// Usage statistics for the completion request.
	Usage CompletionUsage `json:"usage"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
}

type ChatCompletionChoice struct {
	// Any of "stop", "length", "tool_calls", "content_filter", "function_call".
	FinishReason string `json:"finish_reason"`
	// The index of the choice in the list of choices.
	Index int64 `json:"index"`
	// Log probability information for the choice.
	Logprobs ChatCompletionChoiceLogprobs `json:"logprobs"`
	// A chat completion message generated by the model.
	Message ChatCompletionMessage `json:"message"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
}

type ChatCompletionChoiceLogprobs struct {
	// A list of message content tokens with log probability information.
	Content []ChatCompletionTokenLogprob `json:"content"`
	// A list of message refusal tokens with log probability information.
	Refusal []ChatCompletionTokenLogprob `json:"refusal"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
}

type ChatCompletionModeration struct {
	// Moderation for the request input.
	Input ChatCompletionModerationInputUnion `json:"input" api:"required"`
	// Moderation for the generated output.
	Output ChatCompletionModerationOutputUnion `json:"output" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
}

type ChatCompletionModerationInputUnion struct {
	// This field is from variant [ChatCompletionModerationInputModerationResults].
	Model string `json:"model"`
	// This field is from variant [ChatCompletionModerationInputModerationResults].
	Results []ChatCompletionModerationInputModerationResultsResult `json:"results"`
	// Any of "moderation_results", "error".
	Type string `json:"type"`
	// This field is from variant [ChatCompletionModerationInputError].
	Code string `json:"code"`
	// This field is from variant [ChatCompletionModerationInputError].
	Message string `json:"message"`
}

type anyChatCompletionModerationInput interface {
	implChatCompletionModerationInputUnion()
}

func (ChatCompletionModerationInputModerationResults) implChatCompletionModerationInputUnion() {}
func (ChatCompletionModerationInputError) implChatCompletionModerationInputUnion()             {}

func (u ChatCompletionModerationInputUnion) AsAny() anyChatCompletionModerationInput {
	switch u.Type {
	case constant.ModerationTypeResults:
		return u.AsModerationResults()
	case constant.ModerationTypeError:
		return u.AsError()
	}
	return nil
}

func (u ChatCompletionModerationInputUnion) AsModerationResults() (v ChatCompletionModerationInputModerationResults) {
	v.Model = u.Model
	v.Results = u.Results
	v.Type = u.Type
	return v
}

func (u ChatCompletionModerationInputUnion) AsError() (v ChatCompletionModerationInputError) {
	v.Code = u.Code
	v.Message = u.Message
	v.Type = u.Type
	return v
}

type ChatCompletionModerationInputModerationResults struct {
	// The moderation model used to generate the results.
	Model string `json:"model" api:"required"`
	// A list of moderation results.
	Results []ChatCompletionModerationInputModerationResultsResult `json:"results" api:"required"`
	// The object type, which is always `moderation_results`.
	Type string `json:"type" default:"moderation_results"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
}

type ChatCompletionModerationInputModerationResultsResult struct {
	// A dictionary of moderation categories to booleans, True if the input is flagged
	// under this category.
	Categories map[string]bool `json:"categories" api:"required"`
	// Which modalities of input are reflected by the score for each category.
	CategoryAppliedInputTypes map[string][]string `json:"category_applied_input_types" api:"required"`
	// A dictionary of moderation categories to scores.
	CategoryScores map[string]float64 `json:"category_scores" api:"required"`
	// A boolean indicating whether the content was flagged by any category.
	Flagged bool `json:"flagged" api:"required"`
	// The moderation model that produced this result.
	Model string `json:"model" api:"required"`
	// The object type, which was always `moderation_result` for successful moderation
	// results.
	Type string `json:"type" default:"moderation_result"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
}

type ChatCompletionModerationInputError struct {
	// The error code.
	Code string `json:"code" api:"required"`
	// The error message.
	Message string `json:"message" api:"required"`
	// The object type, which is always `error`.
	Type string `json:"type" default:"error"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
}

type ChatCompletionModerationOutputUnion struct {
	// This field is from variant [ChatCompletionModerationOutputModerationResults].
	Model string `json:"model"`
	// This field is from variant [ChatCompletionModerationOutputModerationResults].
	Results []ChatCompletionModerationOutputModerationResultsResult `json:"results"`
	// Any of "moderation_results", "error".
	Type string `json:"type"`
	// This field is from variant [ChatCompletionModerationOutputError].
	Code string `json:"code"`
	// This field is from variant [ChatCompletionModerationOutputError].
	Message string `json:"message"`
}

type anyChatCompletionModerationOutput interface {
	implChatCompletionModerationOutputUnion()
}

func (ChatCompletionModerationOutputModerationResults) implChatCompletionModerationOutputUnion() {}
func (ChatCompletionModerationOutputError) implChatCompletionModerationOutputUnion()             {}

func (u ChatCompletionModerationOutputUnion) AsAny() anyChatCompletionModerationOutput {
	switch u.Type {
	case constant.ModerationTypeResults:
		return u.AsModerationResults()
	case constant.ModerationTypeError:
		return u.AsError()
	}
	return nil
}

func (u ChatCompletionModerationOutputUnion) AsModerationResults() (v ChatCompletionModerationOutputModerationResults) {
	v.Model = u.Model
	v.Results = u.Results
	v.Type = u.Type
	return v
}

func (u ChatCompletionModerationOutputUnion) AsError() (v ChatCompletionModerationOutputError) {
	v.Code = u.Code
	v.Message = u.Message
	v.Type = u.Type
	return v
}

type ChatCompletionModerationOutputModerationResults struct {
	// The moderation model used to generate the results.
	Model string `json:"model" api:"required"`
	// A list of moderation results.
	Results []ChatCompletionModerationOutputModerationResultsResult `json:"results" api:"required"`
	// The object type, which is always `moderation_results`.
	Type string `json:"type" default:"moderation_results"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
}

type ChatCompletionModerationOutputModerationResultsResult struct {
	// A dictionary of moderation categories to booleans, True if the input is flagged
	// under this category.
	Categories map[string]bool `json:"categories" api:"required"`
	// Which modalities of input are reflected by the score for each category.
	CategoryAppliedInputTypes map[string][]string `json:"category_applied_input_types" api:"required"`
	// A dictionary of moderation categories to scores.
	CategoryScores map[string]float64 `json:"category_scores" api:"required"`
	// A boolean indicating whether the content was flagged by any category.
	Flagged bool `json:"flagged" api:"required"`
	// The moderation model that produced this result.
	Model string `json:"model" api:"required"`
	// The object type, which was always `moderation_result` for successful moderation
	// results.
	Type string `json:"type" default:"moderation_result"`
}

type ChatCompletionModerationOutputError struct {
	// The error code.
	Code string `json:"code" api:"required"`
	// The error message.
	Message string `json:"message" api:"required"`
	// The object type, which is always `error`.
	Type string `json:"type" default:"error"`
}

type ChatCompletionServiceTier string

const (
	ChatCompletionServiceTierAuto     ChatCompletionServiceTier = "auto"
	ChatCompletionServiceTierDefault  ChatCompletionServiceTier = "default"
	ChatCompletionServiceTierFlex     ChatCompletionServiceTier = "flex"
	ChatCompletionServiceTierScale    ChatCompletionServiceTier = "scale"
	ChatCompletionServiceTierPriority ChatCompletionServiceTier = "priority"
)

type ChatCompletionTokenLogprob struct {
	// The token.
	Token string `json:"token" api:"required"`
	// A list of integers representing the UTF-8 bytes representation of the token.
	// Useful in instances where characters are represented by multiple tokens and
	// their byte representations must be combined to generate the correct text
	// representation. Can be `null` if there is no bytes representation for the token.
	Bytes []int64 `json:"bytes" api:"required"`
	// The log probability of this token, if it is within the top 20 most likely
	// tokens. Otherwise, the value `-9999.0` is used to signify that the token is very
	// unlikely.
	Logprob float64 `json:"logprob" api:"required"`
	// List of the most likely tokens and their log probability, at this token
	// position. The number of entries may be fewer than the requested `top_logprobs`.
	TopLogprobs []ChatCompletionTokenLogprobTopLogprob `json:"top_logprobs" api:"required"`
}

type ChatCompletionTokenLogprobTopLogprob struct {
	// The token.
	Token string `json:"token" api:"required"`
	// A list of integers representing the UTF-8 bytes representation of the token.
	// Useful in instances where characters are represented by multiple tokens and
	// their byte representations must be combined to generate the correct text
	// representation. Can be `null` if there is no bytes representation for the token.
	Bytes []int64 `json:"bytes" api:"required"`
	// The log probability of this token, if it is within the top 20 most likely
	// tokens. Otherwise, the value `-9999.0` is used to signify that the token is very
	// unlikely.
	Logprob float64 `json:"logprob" api:"required"`
}
