package sdk

type ChatCompletionAudio struct {
	// Unique identifier for this audio response.
	ID string `json:"id" api:"required"`
	// Base64 encoded audio bytes generated by the model, in the format specified in
	// the request.
	Data string `json:"data" api:"required"`
	// The Unix timestamp (in seconds) for when this audio response will no longer be
	// accessible on the server for use in multi-turn conversations.
	ExpiresAt int64 `json:"expires_at" api:"required" format:"unixtime"`
	// Transcript of the audio generated by the model.
	Transcript string `json:"transcript" api:"required"`
}

type ChatCompletionAudioParam struct {
	// Specifies the output audio format. Must be one of `wav`, `mp3`, `flac`, `opus`,
	// or `pcm16`.
	//
	// Any of "wav", "aac", "mp3", "flac", "opus", "pcm16".
	Format ChatCompletionAudioParamFormat `json:"format,omitzero" api:"required"`
	// The voice the model uses to respond. Supported built-in voices are `alloy`,
	// `ash`, `ballad`, `coral`, `echo`, `fable`, `nova`, `onyx`, `sage`, `shimmer`,
	// `marin`, and `cedar`. You may also provide a custom voice object with an `id`,
	// for example `{ "id": "voice_1234" }`.
	Voice ChatCompletionAudioParamVoiceUnion `json:"voice,omitzero" api:"required"`
}

type ChatCompletionAudioParamFormat string

const (
	ChatCompletionAudioParamFormatWAV   ChatCompletionAudioParamFormat = "wav"
	ChatCompletionAudioParamFormatAAC   ChatCompletionAudioParamFormat = "aac"
	ChatCompletionAudioParamFormatMP3   ChatCompletionAudioParamFormat = "mp3"
	ChatCompletionAudioParamFormatFLAC  ChatCompletionAudioParamFormat = "flac"
	ChatCompletionAudioParamFormatOpus  ChatCompletionAudioParamFormat = "opus"
	ChatCompletionAudioParamFormatPcm16 ChatCompletionAudioParamFormat = "pcm16"
)

type ChatCompletionAudioParamVoiceUnion struct {
	OfString *string `json:",omitzero,inline"`
	// Check if union is this variant with
	// !param.IsOmitted(union.OfChatCompletionAudioVoiceString2)
	OfChatCompletionAudioVoiceString2 *string                          `json:",omitzero,inline"`
	OfChatCompletionAudioVoiceID      *ChatCompletionAudioParamVoiceID `json:",omitzero,inline"`
}

func (u *ChatCompletionAudioParamVoiceUnion) asAny() any {
	if u == nil {
		return nil
	}
	if u.OfString != nil {
		return u.OfString
	} else if u.OfChatCompletionAudioVoiceString2 != nil {
		return u.OfChatCompletionAudioVoiceString2
	} else if u.OfChatCompletionAudioVoiceID != nil {
		return u.OfChatCompletionAudioVoiceID
	}
	return nil
}

type ChatCompletionAudioParamVoiceString2 string

const (
	ChatCompletionAudioParamVoiceString2Alloy   ChatCompletionAudioParamVoiceString2 = "alloy"
	ChatCompletionAudioParamVoiceString2Ash     ChatCompletionAudioParamVoiceString2 = "ash"
	ChatCompletionAudioParamVoiceString2Ballad  ChatCompletionAudioParamVoiceString2 = "ballad"
	ChatCompletionAudioParamVoiceString2Coral   ChatCompletionAudioParamVoiceString2 = "coral"
	ChatCompletionAudioParamVoiceString2Echo    ChatCompletionAudioParamVoiceString2 = "echo"
	ChatCompletionAudioParamVoiceString2Sage    ChatCompletionAudioParamVoiceString2 = "sage"
	ChatCompletionAudioParamVoiceString2Shimmer ChatCompletionAudioParamVoiceString2 = "shimmer"
	ChatCompletionAudioParamVoiceString2Verse   ChatCompletionAudioParamVoiceString2 = "verse"
	ChatCompletionAudioParamVoiceString2Marin   ChatCompletionAudioParamVoiceString2 = "marin"
	ChatCompletionAudioParamVoiceString2Cedar   ChatCompletionAudioParamVoiceString2 = "cedar"
)

type ChatCompletionAudioParamVoiceID struct {
	// The custom voice ID, e.g. `voice_1234`.
	ID string `json:"id" api:"required"`
}
