package openai

import "encoding/json"

type ChatCompletionChunk struct {
	// A unique identifier for the chat completion. Each chunk has the same ID.
	ID string `json:"id"`
	// A list of chat completion choices. Can also be empty for the last chunk
	// if you set `stream_options: {"include_usage": true}`.
	Choices []ChatCompletionChunkChoice `json:"choices"`
	// The Unix timestamp (in seconds) of when the chat completion was created.
	// Each chunk has the same timestamp.
	Created int64 `json:"created"`
	// The model to generate the completion.
	Model string `json:"model"`
	// The object type, which is always `chat.completion.chunk`.
	Object string `json:"object"`
	// Usage statistics. Only present on the final chunk when
	// `stream_options: {"include_usage": true}` is set.
	Usage CompletionUsage `json:"usage"`
}

type CompletionUsage struct {
	// Number of tokens in the generated completion.
	CompletionTokens int64 `json:"completion_tokens"`
	// Number of tokens in the prompt.
	PromptTokens int64 `json:"prompt_tokens"`
	// Total number of tokens used in the request (prompt + completion).
	TotalTokens int64 `json:"total_tokens"`
	// Breakdown of tokens used in a completion.
	CompletionTokensDetails CompletionUsageCompletionTokensDetails `json:"completion_tokens_details"`
	// Breakdown of tokens used in the prompt.
	PromptTokensDetails CompletionUsagePromptTokensDetails `json:"prompt_tokens_details"`
	// Raw is the unmodified usage JSON. Provider-specific counters (e.g.
	// DeepSeek's prompt_cache_hit_tokens) can be unmarshaled from it.
	Raw json.RawMessage `json:"-"`
}

func (r *CompletionUsage) UnmarshalJSON(data []byte) error {
	type shadow CompletionUsage
	if err := json.Unmarshal(data, (*shadow)(r)); err != nil {
		return err
	}
	r.Raw = append([]byte(nil), data...)
	return nil
}

type CompletionUsageCompletionTokensDetails struct {
	// Tokens generated by the model for reasoning.
	ReasoningTokens int64 `json:"reasoning_tokens"`
}

type CompletionUsagePromptTokensDetails struct {
	// Cached tokens present in the prompt.
	CachedTokens int64 `json:"cached_tokens"`
}

type ChatCompletionChunkChoice struct {
	// A chat completion delta generated by streamed model responses.
	Delta ChatCompletionChunkChoiceDelta `json:"delta"`
	// The reason the model stopped generating tokens. Empty until the final
	// chunk of a choice.
	//
	// Any of "stop", "length", "tool_calls", "content_filter",
	// "insufficient_system_resource".
	FinishReason string `json:"finish_reason"`
	// The index of the choice in the list of choices.
	Index int64 `json:"index"`
	// Log probability information for the choice.
	Logprobs ChatCompletionChunkChoiceLogprobs `json:"logprobs"`
	// Some providers (e.g. Moonshot) report usage here instead of the
	// standard chunk-level usage field.
	Usage CompletionUsage `json:"usage"`
}

type ChatCompletionChunkChoiceDelta struct {
	// The contents of the chunk message.
	Content string `json:"content"`
	// The chain-of-thought delta emitted by reasoning models. DeepSeek, Qwen,
	// GLM, Kimi and vLLM all use this field name.
	ReasoningContent string `json:"reasoning_content"`
	// Alternative field name for the chain-of-thought delta, used by
	// OpenRouter and newer vLLM versions.
	Reasoning string `json:"reasoning"`
	// Third field name for the chain-of-thought delta, used by some
	// gpt-oss-serving endpoints. Read the first non-empty of the three.
	ReasoningText string `json:"reasoning_text"`
	// The refusal message generated by the model.
	Refusal string `json:"refusal"`
	// The role of the author of this message. Only present on the first chunk.
	Role string `json:"role"`
	// The tool call deltas generated by the model. Accumulate fragments by
	// Index across chunks to reassemble complete tool calls.
	ToolCalls []ChatCompletionChunkChoiceDeltaToolCall `json:"tool_calls"`
	// Raw is the unmodified delta JSON. Provider-specific fields that have no
	// explicit counterpart above can be unmarshaled from it.
	Raw json.RawMessage `json:"-"`
}

func (r *ChatCompletionChunkChoiceDelta) UnmarshalJSON(data []byte) error {
	type shadow ChatCompletionChunkChoiceDelta
	if err := json.Unmarshal(data, (*shadow)(r)); err != nil {
		return err
	}
	r.Raw = append([]byte(nil), data...)
	return nil
}

type ChatCompletionChunkChoiceDeltaToolCall struct {
	Index int64 `json:"index"`
	// The ID of the tool call.
	ID       string                                         `json:"id"`
	Function ChatCompletionChunkChoiceDeltaToolCallFunction `json:"function"`
	// The type of the tool. Currently, only `function` is supported.
	Type string `json:"type"`
}

type ChatCompletionChunkChoiceDeltaToolCallFunction struct {
	// The arguments fragment, to be concatenated across chunks.
	Arguments string `json:"arguments"`
	// The name of the function to call.
	Name string `json:"name"`
}

type ChatCompletionChunkChoiceLogprobs struct {
	// A list of message content tokens with log probability information.
	Content []ChatCompletionTokenLogprob `json:"content"`
	// A list of message refusal tokens with log probability information.
	Refusal []ChatCompletionTokenLogprob `json:"refusal"`
}
